pipeline {
    agent any
        environment {
        MAVEN_HOME = '/opt/maven/apache-maven-3.9.9'
        PATH = "${env.PATH}:${env.MAVEN_HOME}/bin"
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
